[project]
name = "test-python-git-ref-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    'test-python-git-ref-lib @ git+https://github.com/vhiribarren/test-python-git-ref-lib',
]
